### ISSUE TITLE
 This is related to npm not being able to find a file.

### ISSUE THREAD

**Issue by carthikeyan1986** [amplience/cms-javascript-sdk#1]
Hi I am getting error when i am executing. This command npm install 

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/amplience/cms-javascript-sdk.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\emb-kartram\AppData\Roaming\npm-cache\_logs\2019-02-05T16_23_11_383Z-debug.log

My package.json

"dependencies": {
    "lory.js": "2.2.1",
    "showdown": "1.7.1",
	"cms-javascript-sdk": "git@github.com:amplience/cms-javascript-sdk.git"
  },

**Comment by petercoulton** [comment]
This isn't an issue with the SDK. An error message like that usually means that git isn't configured correctly or isn't installed. I can see that you're using windows, here's a [Stackoverflow answer](https://stackoverflow.com/a/23179102/117) that should help you get things setup.
